Update dockerchrome.yml

diff --git a/.github/workflows/dockerchrome.yml b/.github/workflows/dockerchrome.yml
--- a/.github/workflows/dockerchrome.yml
+++ b/.github/workflows/dockerchrome.yml
@@ -73,6 +73,13 @@ jobs:
       run: |
         docker exec -u root selenium-browsers bash -c 'selenium-side-runner /tests/moneygowhere.side'
 
+        if [ $exit_code -ne 0 ]; then
+          echo "selenium-side-runner failed with exit code $exit_code"
+          exit 1  # Fail the step
+        else
+          echo "selenium-side-runner completed successfully"
+        fi
+
         # Clean up the Docker container
         # docker stop selenium-browsers
         # docker rm selenium-browsers
